In [15]:
#knowing each datatype that are in python by intializing values to variables
a=4
b=3.0
c=True
d="string"
e=['hi','bye']
f={"hello","bello"}
g={"age":45,"height":5 }
h=(2,4 ,"hey")
a,b = b,a
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(a,b)

3.0
4
True
string
['hi', 'bye']
{'bello', 'hello'}
{'age': 45, 'height': 5}
(2, 4, 'hey')
<class 'float'>
<class 'int'>
<class 'bool'>
<class 'str'>
<class 'list'>
<class 'set'>
<class 'dict'>
<class 'tuple'>
3.0 4


In [26]:
#to print the factioral of the given number
def fact(n):
     
    if(n>=1):
          f=n*fact (n-1)
    else:
        fact1=1
        return fact1
n=int(input("n="))   
print(fact(n))

n= 4


TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

In [18]:
#to find the sum and average of n numbers
a=int(input("enter the num:"))
temp=a
sum=0
if a<0:
    print("the number is negative.")
else:
    while a>0:
        sum+=a
        a-=1       
print("sum=",sum)
print("avg=",sum/temp)

enter the num: 1


sum= 1
avg= 1.0


In [4]:
#to print the fibonacci series
n = int(input("How many terms you needed "))
m,x = 0, 1
su = 0
if n<= 0:
    print("Please enter a positive integer")
elif n == 1:
    print("Fibonacci sequence upto",n,":")
    print(n1)
else:
    print("Fibonacci sequence:")
    while su < n:
        print(m)
        nth = m + x
        m = x
        x = nth
        su+= 1

How many terms you needed  7


Fibonacci sequence:
0
1
1
2
3
5
8


(4, 3.0, 'Python mania', 'Saina')

In [14]:
#to find the prime numbers between two numbers
x=int(input("enter a number from where u want to start"))
y=int(input("enter a number where u want to stop"))
count=0
#prime number in the sense having only 2 number as exact divisor i.e. 1 and itself can divide that number
for i in range(x,y):
    for j in range(1,i+1):
        if(i%j==0):
            count=count+1
    if(count==2):
        print(i,end=",")
    count=0

enter a number from where u want to start 2
enter a number where u want to stop 4


2,3,

In [16]:
#to find which number is greater
a=int(input("enter the first num: "))
b=int(input("enter the second num: "))
c=int(input("enter the third num: "))
if (a>b) and (a>c):
    print(a,"is greater")
elif (b>c) and (b>a):
            print(b,"is greater")
else:
                print(c,"is greater")

enter the first num:  2
enter the second num:  4
enter the third num:  6


6 is greater


In [17]:

import numpy as np
a = np.arange(60,120).reshape(5,6,2)
a

array([[[ 60,  61],
        [ 62,  63],
        [ 64,  65],
        [ 66,  67],
        [ 68,  69],
        [ 70,  71]],

       [[ 72,  73],
        [ 74,  75],
        [ 76,  77],
        [ 78,  79],
        [ 80,  81],
        [ 82,  83]],

       [[ 84,  85],
        [ 86,  87],
        [ 88,  89],
        [ 90,  91],
        [ 92,  93],
        [ 94,  95]],

       [[ 96,  97],
        [ 98,  99],
        [100, 101],
        [102, 103],
        [104, 105],
        [106, 107]],

       [[108, 109],
        [110, 111],
        [112, 113],
        [114, 115],
        [116, 117],
        [118, 119]]])

In [35]:
b = np.array([x**2 for x in range(1,10+1)])
b


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [37]:
type(b)
b.dtype.name

'int64'

In [20]:
a.ndim

3

In [23]:
def sum(x,y):
    print(x+y)
sum(3,4)

7


In [24]:
x=b"hello"
x

b'hello'

In [25]:
type(x)

bytes

In [26]:
d=None
type(d)

NoneType

In [31]:
m = [[x,x**2,x**3] for x in range (10)]
m

[[  0   0   0]
 [  1   1   1]
 [  2   4   8]
 [  3   9  27]
 [  4  16  64]
 [  5  25 125]
 [  6  36 216]
 [  7  49 343]
 [  8  64 512]
 [  9  81 729]]


In [32]:
a = np.array(m)
print (a)

[[  0   0   0]
 [  1   1   1]
 [  2   4   8]
 [  3   9  27]
 [  4  16  64]
 [  5  25 125]
 [  6  36 216]
 [  7  49 343]
 [  8  64 512]
 [  9  81 729]]
